"""empty message

Revision ID: 9899dd6bd16e
Revises: ef7be5993bf5
Create Date: 2023-01-01 19:42:44.408985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9899dd6bd16e'
down_revision = 'ef7be5993bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.create_unique_constraint('unique_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('unique_email', type_='unique')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
